apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persisitent-volume
  labels:
    env: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres
