apiVersion: v1
kind: Service
metadata:
  name: digdag-master
  labels:
    app: digdag-master
spec:
  selector:
    app: digdag-master
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: null
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digdag-master-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  defaultBackend:
    service:
      name: digdag-master
      port:
        number: 80
