apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config-map
data:
  queries.yaml: |+
    pg_postmaster:
      query: "SELECT count(1) AS queued_tasks FROM tasks"
      metrics:
        - queued_tasks:
            usage: "COUNTER"
            description: "Number of tasks in queue"
