apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-service-monitor
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
  - port: exporter
